name: utm_dash
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_nav_bar: ^5.0.6
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  firebase_messaging: ^14.7.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.8

flutter_native_splash:
  image: assets/images/UTMDASH_LOGO.png
  color: "#ffffff"
  android: true
  ios: true
  web: false
  android_gravity: center
  fullscreen: true
  ios_content_padding: true
  
flutter:

  uses-material-design: true
  assets:
    - assets/images/facebook.png
    - assets/images/twitter.png
    - assets/images/github.png
    - assets/images/UTMDASH_LOGO.png
    - assets/images/defaultUserProfilePic.png
    - assets/images/UTMDASH_LOGO-removebg.png
    - assets/images/Runner_ads.png
