name: utm_dash
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_nav_bar: ^5.0.6
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  firebase_messaging: ^14.7.9
  intl: ^0.19.0
  flutter_native_splash: ^2.3.8
  url_launcher: ^6.2.2
  awesome_notifications: ^0.8.3
  flutter_rating_bar: ^4.0.1
  easy_debounce: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path_android: "assets/images/APPSLOGO2.png"
  image_path_ios: "assets/images/APPSLOGO2.png"
  adaptive_icon_background: "#0xFFBE1C2D"
  android: true
  ios: true

flutter_native_splash:
  image: "assets/images/UTMDASH_LOGO-removebg.png"
  color: "#0xFFBE1C2D"
  android: true
  ios: true
  android_gravity: center
  fullscreen: true
  ios_content_padding: true
  
flutter:

  uses-material-design: true
  assets:
    - assets/images/facebook.png
    - assets/images/twitter.png
    - assets/images/github.png
    - assets/images/UTMDASH_LOGO.png
    - assets/images/defaultUserProfilePic.png
    - assets/images/UTMDASH_LOGO-removebg.png
    - assets/images/Runner_ads.png
    - assets/images/APPSLOGO.png
    - assets/images/APPSLOGO2.png
    - assets/images/NinjaVan_ads.png
    - assets/images/Parcel_Details.png
